### ISSUE TITLE
Multiplication by 2 not necessary

### ISSUE THREAD

**Issue by CapucineBoudin** [clementcaron/game_of_life-caron-cdof2#1]
In the resize_console function, when resizing the console window on Windows (sys.platform.startswith('win')), the cols parameter is multiplied by 2: os.system(f"mode con: cols={cols * 2} lines={rows + 5}"). This is likely done to compensate for the wider characters used to represent live cells ('█') in the grid. However, the multiplication by 2 may not be necessary, as it could result in a distorted grid display. Consider removing the * 2 part of the line.

**Comment by clementcaron** [comment]
Following your feedback, my function should be:

```
def resize_console(rows, cols):
    """Resize the console window to fit the grid."""
    if sys.platform.startswith('win'):
        # Adjusted to not double the columns
        os.system(f"mode con: cols={cols} lines={rows + 5}")
    # Other OS-specific commands can be added if needed.
 ```
 But I think that can be subjective and I leave it here but thank you anyway for your feedback !
