### ISSUE TITLE
Error in count_neighbors function

### ISSUE THREAD

**Issue by CapucineBoudin** [clementcaron/game_of_life-caron-cdof2#2]
The count_neighbors function uses a nested list comprehension to iterate over the 3x3 neighborhood around a cell and sum the live cell values. However, the current implementation includes the current cell itself in the sum, which is incorrect. The condition (i, j) != (0, 0) should be added to the list comprehension to exclude the current cell. The line should be modified as follows:

return sum(grid[(row + i) % rows][(col + j) % cols]
           for i in range(-1, 2) for j in range(-1, 2)
           if (i, j) != (0, 0))

**Comment by clementcaron** [comment]
Thank you for youre review of the count_neighbors function in the code. Your observation is spot-on. The intention of this function is indeed to count the live neighbors surrounding a cell, and mistakenly including the cell itself in this count is an oversight.

The modification you've suggested is precisely what's needed to correct this error. By adding the condition (i, j) != (0, 0) to the list comprehension, we effectively exclude the cell itself from its neighbor count, focusing solely on the surrounding cells. This change ensures that the function accurately counts only the neighbors, aligning with the rules of Conway's Game of Life.

I'm implementing this change immediately, and I appreciate your keen eye in catching this mistake. Thank you !
